

[mammary_epithelial]
raw_data_frags = [
    "",
    "",
    "",
]
combs = [
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],
]
comb_ratios = [ 
    [ 1 ], [ 1 ], [ 1 ], 
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], 
]
train_ratio = 1
N = 512


[human_pancreasn8]
raw_data_frags = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
]
combs = [
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],
]
comb_ratios = [ 
    [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], 
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ], [ 6 ], [ 7 ], 
]
train_ratio = 1
N = 512


[simu_data]
raw_data_frags = [
    "",
    "",
    "",
    "",
]
combs = [
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],
    [ ["rna"] ],

]
comb_ratios = [ 
    [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ],
]
train_ratio = 1
N = 512
